name: integer
description: Dart's native integers in custom bit-width format like i2, i4, i8, i16, i32, ix and u1, u2, u4, u8, u16, u32, ux...
version: 2.0.2
homepage: https://github.com/aldrinsartfactory/integer.dart
repository: https://github.com/aldrinsartfactory/integer.dart

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
