name: integer
description: Use custom bitwidth integers like uint16 or int32 seamlessly via getters and datatypes
version: 1.0.0
homepage: https://github.com/aldrinsartfactory/integer.dart
repository: https://github.com/aldrinsartfactory/integer.dart

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
