name: integer
description: Custom bitwidth integers for Dart.
version: 0.0.1
homepage: https://github.com/aldrinsartfactory/integer.dart
repository: https://github.com/aldrinsartfactory/integer.dart

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
